### ISSUE TITLE
Manually modify or reset counters

### ISSUE THREAD

**Issue by dlackty** [recruit-mp/android-RMP-Appirater#2]
What we want to do is to reset `appLaunchCount` when crash detected to avoid angry user leaving negative comments.

Could it be possible to create few public methods to modify saved preferences? Or a simple reset method should do the trick as well.

Thanks again for making this useful library!

**Comment by yhirano** [comment]
Hello @dlackty 

I try to implement new version(#3). And please check #3 pull request.
Is this code enough for your needs?

**Comment by dlackty** [comment]
@yhirano Just checked the pull request, and yes, it works for our use cases. Thanks for your help!

**Comment by yhirano** [comment]
v1.1.0 released. You can fetch it from maven central several hours later. Thanks.

**Comment by dlackty** [comment]
@yhirano Thank you!
