### ISSUE TITLE
Title missing

### ISSUE THREAD

**Issue by rickybloomfield** [recruit-mp/android-RMP-Appirater#4]
Hi, I installed this and used it per default settings. When used on Android M (Nexus 6p), no title shows up in the view, just the message and buttons. Is this a known issue? Thanks!

**Comment by yhirano** [comment]
I fixed your report issue and released v1.1.1.
You'll find the new version library (v1.1.1) after a few hours later from Maven central repository.

Thanks!

**Comment by rickybloomfield** [comment]
That fixed it - thanks!
